[#ftl]

[@c.page]
    <div class="px-4 py-5 my-5 text-center">
        <img class="d-block mx-auto mb-4" src="/images/school.svg" alt="" />
        <h1 class="display-5 fw-bold text-body-emphasis">Vítejte ve školní evidenci.</h1>
        <div class="col-lg-6 mx-auto">
            <p class="lead mb-4">Školní evidence umožňuje evidovat třídy, studenty, učitele a rodiče.</p>
        </div>
    </div>

[/@c.page]
